name: Actualizar Portafolio Autom치ticamente

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta cada d칤a a las 00:00 UTC
  workflow_dispatch: # Te permite ejecutarlo manualmente desde la pesta침a "Actions" si quieres

permissions:
  contents: write # Permiso vital para que el robot pueda guardar cambios en tu repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 游닌 Descargar tu c칩digo
      uses: actions/checkout@v4

    - name: 游릭 Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 游 Ejecutar script de actualizaci칩n
      run: node generate.js

    - name: 游 Guardar cambios (Commit & Push)
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "游뱄 Auto-update: database.json actualizado"
        file_pattern: database.json
